spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/classicmodels
    username: root
    password: root

mybatis:
  type-aliases-package: com.nubiform.dao
  mapper-locations: classpath:/query/*.xml